language: cpp

matrix:
 include:
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=57
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=58
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=59
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=510
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=511
  - os: osx
    compiler: clang
    env:
     - QT_BASE=latest

before_install:
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-xenial -y; fi
  - if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-xenial -y; fi
  - if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt596-xenial -y; fi
  - if [ "$QT_BASE" = "510" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y; fi
  - if [ "$QT_BASE" = "511" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.2-xenial -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  # install opengl libraries for QtGui
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y;
    fi
  - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
  - if [ "$QT_BASE" = "58" ]; then sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh; fi
  - if [ "$QT_BASE" = "59" ]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
  - if [ "$QT_BASE" = "510" ]; then sudo apt-get install -qq qt510base; source /opt/qt510/bin/qt510-env.sh; fi
  - if [ "$QT_BASE" = "511" ]; then sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh; fi
  - if [ "$QT_BASE" = "latest" ]; then
      brew install qt5;
      brew link --force qt5;
    fi

script:
  - qmake -v
  # run tests
  - mkdir testbuild && cd testbuild
  - qmake -r ../tests/
  - make
  - cd ../
  # compile application
  - mkdir build && cd build
  - qmake -r ../
  - make

notifications:
  email: false
