language: node_js

env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

node_js:
  - "8"
  - "10"
  - "node"

os:
  - linux
  - osx

script:
  - yarn test
  - yarn build

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

jobs:
  include:
    - stage: "Build Package"
      skip_cleanup: true
      os: osx
      script: yarn electron-pack -ml

notifications:
  email: false
