name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: ['12', '*']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install -g yarn
        
      - name: Install, build and test
        env: 
          CI: true
        run: |
          yarn install
          CI=false yarn build
          yarn test --coverage
          
      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        
      - name: Pack on release branch
        if: startsWith(github.ref, 'refs/heads/release') && startsWith(matrix.os, 'macOS')
        run: yarn electron-pack -ml
